name: Build Archive Data

on:
  workflow_dispatch: # 允许手动触发一次以生成初始数据
  schedule:
    - cron: '0 5 1 */3 *' # 每3个月的1号凌晨5点运行

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Commit Archive Data
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          BGM_USER_AGENT: ${{ secrets.BGM_USER_AGENT }}
          BUILD_TYPE: 'archive'
        run: |
          echo '{ "dependencies": { "node-fetch": "^2.7.0", "cheerio": "^1.0.0-rc.12" } }' > package.json
          npm install
          node build_data.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(data): Auto-update archive_data.json'
          file_pattern: 'archive_data.json'
