name: Build Archive Data

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 5 1 */3 *' 

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Synchronize with remote branch
        run: git pull --rebase

      - name: Build Archive Data
        id: build_step # 添加ID以便在失败时引用
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          BGM_USER_AGENT: ${{ secrets.BGM_USER_AGENT }}
          BUILD_TYPE: 'archive' # 您的构建脚本可能需要这个环境变量
        run: |
          echo '{ "dependencies": { "node-fetch": "^2.7.0", "cheerio": "^1.0.0-rc.12" } }' > package.json
          npm install
          node build_data.js

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(data): Auto-update archive data'
          file_pattern: 'archive/*.json'

      
      - name: Notify on failure
        if: failure() && steps.build_step.outcome == 'failure'
        uses: peter-evans/commit-comment@v3
        with:
          body: |
            :x: **Archive Data 构建失败!**

            `Build Archive Data` 工作流在执行时遇到错误。
            请检查最新的Actions运行日志以获取详细信息。

            @${{ github.repository_owner }}
